### ISSUE TITLE
[FEAT] New service: 

### ISSUE THREAD

**Issue by oformoso1974** [tigattack/VeeamNotify#64] opened 2023-09-15 11:43 UTC
### Is your feature request related to a problem?

Google Spaces (Google chat) could be a good addon for the amazing proyect.
We use it as an alert notification solution.

Thanks in advance.

**Comment by tigattack** [comment] 2023-09-15 11:53
Closing as duplicate of #56.

**Closed by tigattack** 2023-09-15 11:53 UTC
Labels: enhancement
